############################################################################
# apps/examples/camtest/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = $(CONFIG_EXAMPLES_CAMTEST_PROGNAME)
PRIORITY  = $(CONFIG_EXAMPLES_CAMTEST_PRIORITY)
STACKSIZE = $(CONFIG_EXAMPLES_CAMTEST_STACKSIZE)
MODULE    = $(CONFIG_EXAMPLES_CAMTEST)

MAINSRC = camtest_main.c

include $(APPDIR)/Application.mk
